
# Use custom format
format = '''
[$username(@$hostname)(:$localip) ](italic blue)$directory(blue)$all
'''
# example
# format = '''
# [â”Œ](bold blue)[$username(@$hostname)(:$localip)](italic blue) $directory(blue)$all
# '''

# Wait 10 seconds for starship to check files under the current directory.
scan_timeout = 10000

# Disable the blank line at the start of the prompt
add_newline = false

[character]
success_symbol = '[ âœ](bold green) '
error_symbol = '[ âœ](bold red) '

[git_branch]
format = 'on [$symbol](blue)[$branch(:$remote_branch)]($style) '
symbol = 'ï„¦ '
truncation_length = 30
style = 'bold italic purple'

[git_state]
merge = '[ï‡ MERGING]'

[git_commit]
tag_symbol = 'ğŸ·'
style = 'yellow'

[git_metrics]
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '
disabled = true

[git_status]
conflicted = '[=:$count]'
# ahead = '[â‡¡:$count]'
behind = '[â‡£:$count]'
diverged = '[â‡•:$count]'
up_to_date = ''
untracked = '[?:$count](red)'
stashed = '[$:$count](purple)'
modified = '[!:$count](yellow)'
staged = '[+:$count](green)'
renamed = '[Â»:$count](blue)'
deleted = '[âœ˜:$count](red)'
typechanged = '|'
style = 'red'

[memory_usage]
format = '\[[(${symbol})${ram}( | ${swap_pct})]($style)\] '
disabled = false
threshold = 80
symbol = 'mem ' # ï”¸
style = 'bold dimmed red'

[java]
symbol = 'ï“¤ '
style = 'green'

[username]
style_user = 'white bold'
style_root = 'black bold'
format = '$user]($style) '
disabled = false

[hostname]
format = '[$ssh_symbol$hostname]($style):'
disabled = false
ssh_symbol = 'ï€£ '

[package]
format = '[\[$version\]](208 bold) '

[cmd_duration]
min_time = 60000 # 60 seconds

[directory]
truncate_to_repo = false
read_only = ':ro'
truncation_symbol = 'â€¦/'

[os]
format = "[($symbol )]($style)"
style = "bold blue"
disabled = false

[os.symbols]
Alpaquita = "îª¢ "
Alpine = "ïŒ€ "
AlmaLinux = "ïŒ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
Artix = "ïŒŸ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ó°›“ "
Gentoo = "ïŒ "
HardenedBSD = "ó°Œ "
Illumos = "ó°ˆ¸ "
Kali = "ïŒ§ "
Linux = "ïŒš "
Mabox = "î¬© "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
OpenBSD = "ó°ˆº "
openSUSE = "ïŒ” "
OracleLinux = "ó°Œ· "
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
RockyLinux = "ïŒ« "
Redox = "ó°€˜ "
Solus = "ó° ³ "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Void = "ïŒ® "
Windows = "ó°² "
